---
title: "Standard login script"
---

```{r echo=FALSE, context = "server"}
# googledrive::drive_auth(cache=".secrets", use_oob = TRUE,
#                         email = account_name)
# password_df <- suppressMessages(googlesheets4::read_sheet(credentials))

user_id <- "not initialized"
password_df <- tibble::tribble(
  ~ id, ~ password,
  "Danny", "mosaic",
  "Mindo", "dog"
)
password_df <- readr::read_csv(credentials)
```


`r textOutput("login_message")`
`r '<table><tr><td>ID:</td><td><input id="userID" type="text" class="form-control" value=""/></td><td>     Password:</td><td><input id="password" type="password" class="form-control" value="" /></td><td></td></tr></table>'`


```{r echo = FALSE}
conditionalPanel(
  condition =
    paste0("input.userID == 'instructor' && input.password == '", 
           instructor_key, "'"),
  downloadLink("get_submissions",  label="Download submissions")
)
```

```{r context = "server"}
valid_id <- reactive({
  cat("In  login shiny\n")
  user_row <- which(input$userID == password_df$id)

  return(! length(user_row) == 0)
})
valid_password <- reactive({
  if (is.null(input$password)) return(FALSE)
  user_row <- which(input$userID == password_df$id)

  if (length(user_row) == 0) FALSE
  else {
    input$password == password_df$password[user_row] ||
      password_df == "open_login"
  }
})

# set the learnr logging function
observe({
  if (valid_id()) {
    
    if (valid_password())  {
      user_identification <- isolate(input$userID)
    } else {
      user_identification <- paste("Unauthenticated", isolate(input$userID))
    }
    options(tutorial.event_recorder =
              make_recorder(store_fun = storage_actions$write,
                            markr_id = user_identification))
            
  }
})

output$login_message <-
  renderText({ 
  
      if (valid_id()  && valid_password()) {
        "Login SUCCESSFUL."
      } else if (valid_id()) {
        "Valid ID but password not yet correct"
      } else if (nchar(input$userID) > 1) {"Invalid user ID"}
      else {
        "Please log in."
      }
    })

# Link to download submissions ...
output$get_submissions <- downloadHandler(
  filename = function() {
    paste0("submissions-", Sys.Date(), ".csv")
  },
  content = storage_actions$read_submissions
)
```

